### ISSUE TITLE
Update required Rust version

### ISSUE THREAD

**Issue by michaelkuhn** [julea-io/haura#19]
According to the README, 1.53.0 should be enough but it seems that we require something between 1.60.0 (which fails) and 1.65.0 (which works) nowadays.

**Comment by jwuensche** [comment]
Yeah, we're using some features which were not stabilized back then. The current MSRV is 1.62 due to the addition of `total_cmp`. We might consider bumping this in the README, although I would suggest changing the guarantee to the latest stable version, since this a research stack after all. The compiler should always work with older code so we atleast don't have to worry about faulty documentation. Do you have any preference?

**Comment by michaelkuhn** [comment]
Recommending the latest version sounds good to me. Can we still add something to one of the TOML files indicating that at least 1.62.0 is needed so we get a useful error message instead of a failed build?

**Comment by jwuensche** [comment]
Yeah we can add to the Cargo.toml of betree the `rust-version` field which does exactly that (https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field). Also, just saw that someone implemented a binary search for this https://github.com/foresterre/cargo-msrv :D They also have a verification command to see if the `rust-version` field is still valid. Since this is very little effort, we can put the verification in a small additional job in the CI.
